// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MonitoringConfigurator.Migrations
{
    [DbContext(typeof(MonitoringConfigurator.Data.AppDbContext))]
    [Migration("20250904174927_AddLensToProducts")]
    partial class AddLensToProducts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Intentionally minimal; EF will regenerate snapshot on real migration add.
        }
    }
}
